//GET 137 GAMES FROM BACK
export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS"; 
export const GET_GAMES_ERROR = "GET_GAMES_ERROR"
// SEARCH POR QUERY
export const SEARCH_GAMES = "SEARCH_GAMES"
export const SEARCH_GAMES_SUCCESS = "SEARCH_GAMES_SUCCESS"
export const SEARCH_GAMES_ERROR = "SEARCH_GAMES_ERROR"
