//GET 137 GAMES FROM BACK
export const GET_ALL_VIDEOGAMES = "GET_ALL_VIDEOGAMES";
export const GET_GAMES_SUCCESS = "GET_GAMES_SUCCESS"; 
export const GET_GAMES_ERROR = "GET_GAMES_ERROR"
// SEARCH POR QUERY
export const SEARCH_GAMES = "SEARCH_GAMES"
export const SEARCH_GAMES_SUCCESS = "SEARCH_GAMES_SUCCESS"
export const SEARCH_GAMES_ERROR = "SEARCH_GAMES_ERROR"
// ORDER BY
export const ORDER_BY = "ORDER_BY"
export const ORDER_BY_SUCCESS = "ORDER_BY_SUCCESS"
export const ORDER_BY_ERROR = "ORDER_BY_ERROR"
// GETTING GENRES FROM DB
export const GET_GENRE = "GET_GENRE"
export const GET_GENRE_SUCCESS = "GET_GENRE_SUCCESS"
export const GET_GENRE_ERROR = "GET_GENRE_ERROR"
//RESET
export const RESET = "RESET"

//ordenamiento
export const ORDER_ASC_NAME    = "ORDER_ASC_NAME"
export const ORDER_ASC_RATING  = "ORDER_ASC_RATING"
export const ORDER_DESC_NAME   = "ORDER_DESC_NAME"
export const ORDER_DESC_RATING = "ORDER_DESC_RATING"